arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
description: "MQTT-gateway for SAIC cars like MG5, ZS EV or Marvel R"
name: "SAIC MQTT Gateway (Java)"
image: "saicismartapi/saic-java-mqtt-gateway"
url: "https://github.com/SAIC-iSmart-API/saic-home-assistant-addon"
slug: "saic_java_mqtt_gateway"
stage: "stable"
version: "0.2.1"
legacy: true
options:
  MQTT_URI: "tcp://localhost:1883"
  MQTT_USER: null
  MQTT_PASSWORD: null
  SAIC_USER: null
  SAIC_PASSWORD: null
  SAIC_URI: ""
  ABRP_API_KEY: ""
  ABRP_USER_TOKEN: ""
schema:
  MQTT_URI: str
  MQTT_USER: str
  MQTT_PASSWORD: password
  SAIC_USER: str
  SAIC_PASSWORD: password
  SAIC_URI: str?
  ABRP_API_KEY: str?
  ABRP_USER_TOKEN: str?
init: false
host_network: true
